### ISSUE TITLE
Please give info on the environment confguration

### ISSUE THREAD

**Issue by infinite-Joy** [quora/asynq#3]
I see that there are some dependencies like cython. Please provide a requirements.txt and also update the values in setup.py so that they also get installed while doing the pip install

**Comment by JelleZijlstra** [comment]
The requirements are qcore (which is already in setup.py), six (which is also a qcore dependency), mock (for Python 2 only), and Cython. It's not clear to me how to declare the Cython dependency in setup.py, because setup.py itself needs to import Cython to call cythonize(). I'll look more into ways to handle this, but pull requests would also be appreciated.

**Comment by SurenNihalani** [comment]
@JelleZijlstra , Is this resolved with setuptools' Extension module?

**Comment by JelleZijlstra** [comment]
Yes.
