### ISSUE TITLE
Nested contexts don't work right if two contexts are __eq__ to each other

### ISSUE THREAD

**Issue by emorphis** [quora/asynq#72]
When we leave the context, we'll call the _context list's remove function, which will remove the first context that's __eq__ to the given one. This can mess up the nesting order, e.g.:

```
x = [C(0), C(1), C(0)]
x.remove(x[2])
```

will leave [C(1), C(0)] when the intention is to leave [C(0), C(1)].

**Comment by JelleZijlstra** [comment]
This seems like a bug; we should compare these objects by identity instead.

A possible implementation would be store the `id()` of the objects instead of the objects themselves.

Another related optimization could be to use an OrderedDict (or a plain dict in 3.6 or higher), so that we keep the collection ordered but make it possible to add/remove contexts efficiently.

**Comment by emorphis** [comment]
fixed in https://github.com/quora/asynq/pull/73
